### ISSUE TITLE
More dependinces from Select2

### ISSUE THREAD

**Issue by loveorigami** [2amigos/yii2-editable-widget#10]
Dear Antonio!
After installing editable-widget I have more dependinces from Select2. 
It is not good, because I not use Simfony, components etc.From one of them I have mistake in console...

Please, correct dependencies with Select2.
May be better use Select2 as bower without composer dependencies?

**Comment by SDKiller** [comment]
+1

Numerous dependencies, including extra `jquery` + installation via `component-installer` *vs* **single bower package**

![qip shot - screen 568 20 02 15](https://cloud.githubusercontent.com/assets/2150916/6288035/33a04494-b927-11e4-9e28-fec657f7fc60.png)
