### ISSUE TITLE
Assigning function to url param.

### ISSUE THREAD

**Issue by alagodich** [2amigos/yii2-editable-widget#11]
Hello

I am trying to assign function to editable url property,
as it is being stated here: https://github.com/2amigos/yii2-editable-widget/blob/master/Editable.php#L43

But when it comes to https://github.com/2amigos/yii2-editable-widget/blob/master/Editable.php#L174
It always creates path without checking if there is a function, not url.

It happens here:
https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseUrl.php#L134
It just concatenates everything we passed there with the current route. 

For example, if i set in the search controller:
```php
"url" => "function(params) {}"
```
I will get:
```php
"url":"/search/function(params) {}"
```

**Comment by alagodich** [comment]
Maybe i am wrong, but we could probably check if the value in url param is JsExpression?
and pass it like:
```
'url' => new JsExpression($script)
```

**Comment by tonydspaniard** [comment]
You are right @alagodich I'll try to tackle it asap but I am quite busy atm
