### ISSUE TITLE
Unable to install this package

### ISSUE THREAD

**Issue by trejder** [2amigos/yii2-editable-widget#19]
Exactly the same problem, as in case of [`yii2-ckeditor-widget`](https://github.com/2amigos/yii2-ckeditor-widget/issues/29#issuecomment-91151762). Command:

```
composer require 2amigos/yii2-editable-widget:~1.0
```

gives:

```
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package 2amigos/yii2-editable-widget could not be found in a
ny version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your min
imum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> f
or more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common
 problems.

Installation failed, reverting ./composer.json to its original content.
```

"Fixed" by using either of these:

```
composer require 2amigos/yii2-editable-widget
composer require 2amigos/yii2-editable-widget:*
composer require 2amigos/yii2-editable-widget:dev-master
```

I think, you should validate all your packages' installation instructions, to check whether using `~1.0` as version prefix is correct / required?

**Comment by tonydspaniard** [comment]
apologies @trejder the version ~1.0 is not done yet. We need to include the tests for the version update to appear.

**Comment by trejder** [comment]
Antonio, that is perfectly fine. I just wanted to notice you, that in this case you should modify `README.md` to not give users instructions to use version `~1.0` (as you do now). Tell them (in that file) to use something else (ready, stable?) to not confuse beginners.

In other words -- I have copy&paste code from `README.md` to my command-line and... bang! This should not happen IMHO.

**Comment by tonydspaniard** [comment]
You are right @trejder Thanks

**Comment by tonydspaniard** [comment]
I think this issue is already outdated.
