### ISSUE TITLE
Select2.js not found

### ISSUE THREAD

**Issue by alexgutnik** [2amigos/yii2-editable-widget#32]
Hi!

After update to version 1.1.0 from 1.0.1 the issue appeared:

> site.com/assets/24b03a89/select2.js 404 (Not Found)

Please, update **$sourcePath** in asset

**Comment by tonydspaniard** [comment]
Thanks!

**Comment by tonydspaniard** [comment]
@alexgutnik is done... nevertheless, I am currently revamping all our extensions and next version will include tests. Apologies if is not working as expected and how it should be. But is on my plans, just a bit behind on the queue.
